config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :arrived_qatars
  resources :transits
  resources :arriveds
  resources :mail_items
  resources :locations
  resources :users
      get :be_admin, on: :member
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/transit.rb
class Transit < ApplicationRecord
	has_many :mail_items
end

app/controllers/transits_controller.rb
class TransitsController < ApplicationController
  before_action :set_transit, only: [:show, :edit, :update, :destroy]

  # GET /transits
  # GET /transits.json
  def index
    @transits = Transit.all
  end

  # GET /transits/1
  # GET /transits/1.json
  def show
  end

  # GET /transits/new
  def new
    @transit = Transit.new
  end

  # GET /transits/1/edit
  def edit
  end

  # POST /transits
  # POST /transits.json
  def create
    @transit = Transit.new(transit_params)

    respond_to do |format|
      if @transit.save
        format.html { redirect_to @transit, notice: 'Transit was successfully created.' }
        format.json { render :show, status: :created, location: @transit }
      else
        format.html { render :new }
        format.json { render json: @transit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transits/1
  # PATCH/PUT /transits/1.json
  def update
    respond_to do |format|
      if @transit.update(transit_params)
        format.html { redirect_to @transit, notice: 'Transit was successfully updated.' }
        format.json { render :show, status: :ok, location: @transit }
      else
        format.html { render :edit }
        format.json { render json: @transit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transits/1
  # DELETE /transits/1.json
  def destroy
    @transit.destroy
    respond_to do |format|
      format.html { redirect_to transits_url, notice: 'Transit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transit
      @transit = Transit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transit_params
      params.require(:transit).permit(:id, :date_delivered, :sender_string, :description, :comment, :shipping_weight, :arrived)
    end
end

app/helpers/transits_helper.rb
module TransitsHelper
end

app/views/transits/_form.html.erb
<%= form_for(transit) do |f| %>
  <% if transit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transit.errors.count, "error") %> prohibited this transit from being saved:</h2>

      <ul>
      <% transit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %>
    <%= f.text_field :id %>
  </div>

  <div class="field">
    <%= f.label :date_delivered %>
    <%= f.text_field :date_delivered %>
  </div>

  <div class="field">
    <%= f.label :sender_string %>
    <%= f.text_field :sender_string %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="field">
    <%= f.label :shipping_weight %>
    <%= f.number_field :shipping_weight %>
  </div>

  <div class="field">
    <%= f.label :arrived %>
    <%= f.check_box :arrived %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transits/edit.html.erb
<h1>Editing Transit</h1>

<%= render 'form', transit: @transit %>

<%= link_to 'Show', @transit %> |
<%= link_to 'Back', transits_path %>

app/views/transits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transits</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Date delivered</th>
      <th>Sender string</th>
      <th>Description</th>
      <th>Comment</th>
      <th>Shipping weight</th>
      <th>Arrived</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transits.each do |transit| %>
      <tr>
        <td><%= transit.id %></td>
        <td><%= transit.date_delivered %></td>
        <td><%= transit.sender_string %></td>
        <td><%= transit.description %></td>
        <td><%= transit.comment %></td>
        <td><%= transit.shipping_weight %></td>
        <td><%= transit.arrived %></td>
        <td><%= link_to 'Show', transit %></td>
        <td><%= link_to 'Edit', edit_transit_path(transit) %></td>
        <td><%= link_to 'Destroy', transit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transit', new_transit_path %>

app/views/transits/new.html.erb
<h1>New Transit</h1>

<%= render 'form', transit: @transit %>

<%= link_to 'Back', transits_path %>

app/views/transits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @transit.id %>
</p>

<p>
  <strong>Date delivered:</strong>
  <%= @transit.date_delivered %>
</p>

<p>
  <strong>Sender string:</strong>
  <%= @transit.sender_string %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transit.description %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @transit.comment %>
</p>

<p>
  <strong>Shipping weight:</strong>
  <%= @transit.shipping_weight %>
</p>

<p>
  <strong>Arrived:</strong>
  <%= @transit.arrived %>
</p>

<%= link_to 'Edit', edit_transit_path(@transit) %> |
<%= link_to 'Back', transits_path %>