config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :arrived_qatars
  resources :transits
  resources :arriveds
  resources :mail_items
  resources :locations
  resources :users
      get :be_admin, on: :member
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/history.rb
class History < ApplicationRecord
	has_many :users
	has_many :mail_items
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:date_arrived_pittsburgh, :date_delivered, :date_arrived_qatar, :sender, :description, :comment, :shipping_weight, :discarded, :delivered)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_for(history) do |f| %>
  <% if history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_arrived_pittsburgh %>
    <%= f.text_field :date_arrived_pittsburgh %>
  </div>

  <div class="field">
    <%= f.label :date_delivered %>
    <%= f.text_field :date_delivered %>
  </div>

  <div class="field">
    <%= f.label :date_arrived_qatar %>
    <%= f.text_field :date_arrived_qatar %>
  </div>

  <div class="field">
    <%= f.label :sender %>
    <%= f.text_field :sender %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="field">
    <%= f.label :shipping_weight %>
    <%= f.number_field :shipping_weight %>
  </div>

  <div class="field">
    <%= f.label :discarded %>
    <%= f.check_box :discarded %>
  </div>

  <div class="field">
    <%= f.label :delivered %>
    <%= f.check_box :delivered %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Histories</h1>

<table>
  <thead>
    <tr>
      <th>Date arrived pittsburgh</th>
      <th>Date delivered</th>
      <th>Date arrived qatar</th>
      <th>Sender</th>
      <th>Description</th>
      <th>Comment</th>
      <th>Shipping weight</th>
      <th>Discarded</th>
      <th>Delivered</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.date_arrived_pittsburgh %></td>
        <td><%= history.date_delivered %></td>
        <td><%= history.date_arrived_qatar %></td>
        <td><%= history.sender %></td>
        <td><%= history.description %></td>
        <td><%= history.comment %></td>
        <td><%= history.shipping_weight %></td>
        <td><%= history.discarded %></td>
        <td><%= history.delivered %></td>
        <td><%= link_to 'Show', history %></td>
        <td><%= link_to 'Edit', edit_history_path(history) %></td>
        <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History', new_history_path %>

app/views/histories/new.html.erb
<h1>New History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date arrived pittsburgh:</strong>
  <%= @history.date_arrived_pittsburgh %>
</p>

<p>
  <strong>Date delivered:</strong>
  <%= @history.date_delivered %>
</p>

<p>
  <strong>Date arrived qatar:</strong>
  <%= @history.date_arrived_qatar %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @history.sender %>
</p>

<p>
  <strong>Description:</strong>
  <%= @history.description %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @history.comment %>
</p>

<p>
  <strong>Shipping weight:</strong>
  <%= @history.shipping_weight %>
</p>

<p>
  <strong>Discarded:</strong>
  <%= @history.discarded %>
</p>

<p>
  <strong>Delivered:</strong>
  <%= @history.delivered %>
</p>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>