config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :arrived_qatars
  resources :transits
  resources :arriveds
  resources :mail_items
  resources :locations
  resources :users
      get :be_admin, on: :member
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/arrived_qatar.rb
class ArrivedQatar < ApplicationRecord
	belongs_to :user
	has_many :mail_items
end

app/controllers/arrived_qatars_controller.rb
class ArrivedQatarsController < ApplicationController
  before_action :set_arrived_qatar, only: [:show, :edit, :update, :destroy]

  # GET /arrived_qatars
  # GET /arrived_qatars.json
  def index
    @arrived_qatars = ArrivedQatar.all
  end

  # GET /arrived_qatars/1
  # GET /arrived_qatars/1.json
  def show
  end

  # GET /arrived_qatars/new
  def new
    @arrived_qatar = ArrivedQatar.new
  end

  # GET /arrived_qatars/1/edit
  def edit
  end

  # POST /arrived_qatars
  # POST /arrived_qatars.json
  def create
    @arrived_qatar = ArrivedQatar.new(arrived_qatar_params)

    respond_to do |format|
      if @arrived_qatar.save
        format.html { redirect_to @arrived_qatar, notice: 'Arrived qatar was successfully created.' }
        format.json { render :show, status: :created, location: @arrived_qatar }
      else
        format.html { render :new }
        format.json { render json: @arrived_qatar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arrived_qatars/1
  # PATCH/PUT /arrived_qatars/1.json
  def update
    respond_to do |format|
      if @arrived_qatar.update(arrived_qatar_params)
        format.html { redirect_to @arrived_qatar, notice: 'Arrived qatar was successfully updated.' }
        format.json { render :show, status: :ok, location: @arrived_qatar }
      else
        format.html { render :edit }
        format.json { render json: @arrived_qatar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arrived_qatars/1
  # DELETE /arrived_qatars/1.json
  def destroy
    @arrived_qatar.destroy
    respond_to do |format|
      format.html { redirect_to arrived_qatars_url, notice: 'Arrived qatar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arrived_qatar
      @arrived_qatar = ArrivedQatar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arrived_qatar_params
      params.require(:arrived_qatar).permit(:date_arrived_pittsburgh, :date_delivered, :date_arrived_qatar, :sender, :description, :comment, :shipping_weight, :delivered)
    end
end

app/helpers/arrived_qatars_helper.rb
module ArrivedQatarsHelper
end

app/views/arrived_qatars/_form.html.erb
<%= form_for(arrived_qatar) do |f| %>
  <% if arrived_qatar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(arrived_qatar.errors.count, "error") %> prohibited this arrived_qatar from being saved:</h2>

      <ul>
      <% arrived_qatar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_arrived_pittsburgh %>
    <%= f.text_field :date_arrived_pittsburgh %>
  </div>

  <div class="field">
    <%= f.label :date_delivered %>
    <%= f.text_field :date_delivered %>
  </div>

  <div class="field">
    <%= f.label :date_arrived_qatar %>
    <%= f.text_field :date_arrived_qatar %>
  </div>

  <div class="field">
    <%= f.label :sender %>
    <%= f.text_field :sender %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="field">
    <%= f.label :shipping_weight %>
    <%= f.number_field :shipping_weight %>
  </div>

  <div class="field">
    <%= f.label :delivered %>
    <%= f.check_box :delivered %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/arrived_qatars/edit.html.erb
<h1>Editing Arrived Qatar</h1>

<%= render 'form', arrived_qatar: @arrived_qatar %>

<%= link_to 'Show', @arrived_qatar %> |
<%= link_to 'Back', arrived_qatars_path %>

app/views/arrived_qatars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Arrived Qatars</h1>

<table>
  <thead>
    <tr>
      <th>Date arrived pittsburgh</th>
      <th>Date delivered</th>
      <th>Date arrived qatar</th>
      <th>Sender</th>
      <th>Description</th>
      <th>Comment</th>
      <th>Shipping weight</th>
      <th>Delivered</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arrived_qatars.each do |arrived_qatar| %>
      <tr>
        <td><%= arrived_qatar.date_arrived_pittsburgh %></td>
        <td><%= arrived_qatar.date_delivered %></td>
        <td><%= arrived_qatar.date_arrived_qatar %></td>
        <td><%= arrived_qatar.sender %></td>
        <td><%= arrived_qatar.description %></td>
        <td><%= arrived_qatar.comment %></td>
        <td><%= arrived_qatar.shipping_weight %></td>
        <td><%= arrived_qatar.delivered %></td>
        <td><%= link_to 'Show', arrived_qatar %></td>
        <td><%= link_to 'Edit', edit_arrived_qatar_path(arrived_qatar) %></td>
        <td><%= link_to 'Destroy', arrived_qatar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Arrived Qatar', new_arrived_qatar_path %>

app/views/arrived_qatars/new.html.erb
<h1>New Arrived Qatar</h1>

<%= render 'form', arrived_qatar: @arrived_qatar %>

<%= link_to 'Back', arrived_qatars_path %>

app/views/arrived_qatars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date arrived pittsburgh:</strong>
  <%= @arrived_qatar.date_arrived_pittsburgh %>
</p>

<p>
  <strong>Date delivered:</strong>
  <%= @arrived_qatar.date_delivered %>
</p>

<p>
  <strong>Date arrived qatar:</strong>
  <%= @arrived_qatar.date_arrived_qatar %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @arrived_qatar.sender %>
</p>

<p>
  <strong>Description:</strong>
  <%= @arrived_qatar.description %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @arrived_qatar.comment %>
</p>

<p>
  <strong>Shipping weight:</strong>
  <%= @arrived_qatar.shipping_weight %>
</p>

<p>
  <strong>Delivered:</strong>
  <%= @arrived_qatar.delivered %>
</p>

<%= link_to 'Edit', edit_arrived_qatar_path(@arrived_qatar) %> |
<%= link_to 'Back', arrived_qatars_path %>