config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :arrived_qatars
  resources :transits
  resources :arriveds
  resources :mail_items
  resources :locations
  resources :users
      get :be_admin, on: :member
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/arrived.rb
class Arrived < ApplicationRecord
	## this file represents the table arrived in pittsburgh.
	belongs_to :user
	has_many :mail_items
	validates :id, presence: true, uniqueness: true
end

app/controllers/arriveds_controller.rb
class ArrivedsController < ApplicationController
  ## this file represents the table arrived in pittsburgh.
  before_action :set_arrived, only: [:show, :edit, :update, :destroy]

  # GET /arriveds
  # GET /arriveds.json
  def index
    @arriveds = Arrived.all
  end

  # GET /arriveds/1
  # GET /arriveds/1.json
  def show
  end

  # GET /arriveds/new
  def new
    @arrived = Arrived.new
  end

  # GET /arriveds/1/edit
  def edit
  end

  # POST /arriveds
  # POST /arriveds.json
  def create
    @arrived = Arrived.new(arrived_params)

    respond_to do |format|
      if @arrived.save
        format.html { redirect_to @arrived, notice: 'Arrived was successfully created.' }
        format.json { render :show, status: :created, location: @arrived }
      else
        format.html { render :new }
        format.json { render json: @arrived.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arriveds/1
  # PATCH/PUT /arriveds/1.json
  def update
    respond_to do |format|
      if @arrived.update(arrived_params)
        format.html { redirect_to @arrived, notice: 'Arrived was successfully updated.' }
        format.json { render :show, status: :ok, location: @arrived }
      else
        format.html { render :edit }
        format.json { render json: @arrived.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arriveds/1
  # DELETE /arriveds/1.json
  def destroy
    @arrived.destroy
    respond_to do |format|
      format.html { redirect_to arriveds_url, notice: 'Arrived was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arrived
      @arrived = Arrived.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arrived_params
      params.require(:arrived).permit(:id, :date_arrived_pittsburgh, :sender_string, :description, :comment, :shipping_weight, :discard)
    end
end

app/helpers/arriveds_helper.rb
module ArrivedsHelper
end

app/views/arriveds/_form.html.erb
<%= form_for(arrived) do |f| %>
  <% if arrived.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(arrived.errors.count, "error") %> prohibited this arrived from being saved:</h2>

      <ul>
      <% arrived.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %>
    <%= f.text_field :id %>
  </div>

  <div class="field">
    <%= f.label :date_arrived_pittsburgh %>
    <%= f.text_field :date_arrived_pittsburgh %>
  </div>

  <div class="field">
    <%= f.label :sender_string %>
    <%= f.text_field :sender_string %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="field">
    <%= f.label :shipping_weight %>
    <%= f.number_field :shipping_weight %>
  </div>

  <div class="field">
    <%= f.label :discard %>
    <%= f.check_box :discard %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/arriveds/edit.html.erb
<h1>Editing Arrived</h1>

<%= render 'form', arrived: @arrived %>

<%= link_to 'Show', @arrived %> |
<%= link_to 'Back', arriveds_path %>

app/views/arriveds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Arriveds</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Date arrived pittsburgh</th>
      <th>Sender string</th>
      <th>Description</th>
      <th>Comment</th>
      <th>Shipping weight</th>
      <th>Discard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arriveds.each do |arrived| %>
      <tr>
        <td><%= arrived.id %></td>
        <td><%= arrived.date_arrived_pittsburgh %></td>
        <td><%= arrived.sender_string %></td>
        <td><%= arrived.description %></td>
        <td><%= arrived.comment %></td>
        <td><%= arrived.shipping_weight %></td>
        <td><%= arrived.discard %></td>
        <td><%= link_to 'Show', arrived %></td>
        <td><%= link_to 'Edit', edit_arrived_path(arrived) %></td>
        <td><%= link_to 'Destroy', arrived, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Arrived', new_arrived_path %>

app/views/arriveds/new.html.erb
<h1>New Arrived</h1>

<%= render 'form', arrived: @arrived %>

<%= link_to 'Back', arriveds_path %>

app/views/arriveds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @arrived.id %>
</p>

<p>
  <strong>Date arrived pittsburgh:</strong>
  <%= @arrived.date_arrived_pittsburgh %>
</p>

<p>
  <strong>Sender string:</strong>
  <%= @arrived.sender_string %>
</p>

<p>
  <strong>Description:</strong>
  <%= @arrived.description %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @arrived.comment %>
</p>

<p>
  <strong>Shipping weight:</strong>
  <%= @arrived.shipping_weight %>
</p>

<p>
  <strong>Discard:</strong>
  <%= @arrived.discard %>
</p>

<%= link_to 'Edit', edit_arrived_path(@arrived) %> |
<%= link_to 'Back', arriveds_path %>